#!/usr/bin/env python3
"""Receiver-normal restart contract for spiral branch-chart candidates."""

from __future__ import annotations

import argparse
import json


CANDIDATES = {
    "vp1": {
        "label": "VP-1",
        "sidecar": "spiral-vp1-current-interval-rows.json",
        "active_labels": ["P_1", "P_2", "P_3", "S_1"],
    },
    "a1": {
        "label": "A1",
        "sidecar": "spiral-a1-current-interval-rows.json",
        "active_labels": ["P_1", "P_2", "P_3", "S_1"],
    },
}


def build_contract(candidate_key: str) -> dict:
    candidate = CANDIDATES[candidate_key]
    return {
        "candidate": candidate_key,
        "label": candidate["label"],
        "status": "receiver_normal_restart_required",
        "claim_level": "restart target, not force/action evidence",
        "sidecar": candidate["sidecar"],
        "active_labels": candidate["active_labels"],
        "surviving_rows": [
            "retained_root_labels",
            "inactive_gaps",
            "finite_memory_depth",
            "source_normal_transversality_floor",
        ],
        "required_current_law_rows": [
            "retained_root_box",
            "D_s_interval",
            "D_t_interval",
            "W_rec_interval",
            "receiver_normal_radial_interval",
            "receiver_normal_tangential_interval",
            "negative_control_missing_D_t",
        ],
        "promotion_rule": (
            "No spiral branch-chart force, action, radial, tangential, or "
            "compatibility row may pass or fail until it is redriven from "
            "same-record D_s, D_t, and W_rec=abs(D_t/D_s)."
        ),
    }


def emit_markdown(contract: dict) -> str:
    labels = ", ".join(contract["active_labels"])
    surviving = "\n".join(f"- `{row}`" for row in contract["surviving_rows"])
    required = "\n".join(f"- `{row}`" for row in contract["required_current_law_rows"])
    return f"""# Spiral Branch-Chart Receiver-Normal Restart Contract

Generated by `spiral_branch_chart_certificate.py`.

## Status

- Candidate: `{contract['label']}`.
- Certificate status: `{contract['status']}`.
- Claim level: `{contract['claim_level']}`.
- Sidecar: `{contract['sidecar']}`.
- Active labels: `{labels}`.

## Surviving Rows

{surviving}

These rows are topology and transversality diagnostics only. They do not supply
current Master EOM force/action evidence by themselves.

## Required Current-Law Rows

{required}

## Promotion Rule

{contract['promotion_rule']}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--candidate", choices=sorted(CANDIDATES), default="vp1")
    parser.add_argument("--format", choices=["json", "markdown"], default="json")
    parser.add_argument("--interval-proof-rows", help="Accepted for CLI compatibility; ignored.")
    args, _unknown = parser.parse_known_args()

    contract = build_contract(args.candidate)
    if args.format == "markdown":
        print(emit_markdown(contract))
    else:
        print(json.dumps(contract, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
