import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

import { BORG_ASSEMBLY_RECORD_CATALOG } from "../src/apps/borg/BorgAssemblyRecordCatalog.js";
import { verifyAssemblyRecordByteIdentity } from "../scripts/borg/verify-assembly-record-byte-identity.mjs";

const root = path.resolve(import.meta.dirname, "..");

test("all catalogued Borg record bytes match the registry and collection before publication", () => {
  const result = verifyAssemblyRecordByteIdentity({ rootDir: root });
  assert.equal(result.status, "passed");
  assert.equal(result.verifiedRecords, 145);
  assert.ok(result.verifiedBytes > 100_000_000);
});

test("Borg record byte verification fails closed on changed generated bytes", () => {
  const target = BORG_ASSEMBLY_RECORD_CATALOG.entries[0].recordUrl;
  const targetPath = path.resolve(root, target);
  assert.throws(
    () => verifyAssemblyRecordByteIdentity({
      rootDir: root,
      readBytes: (absolutePath) => {
        const bytes = fs.readFileSync(absolutePath);
        return absolutePath === targetPath ? Buffer.concat([bytes, Buffer.from(" ")]) : bytes;
      },
    }),
    /SHA-256 .* does not match registry/u,
  );
});
