import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { execFileSync, spawnSync } from "node:child_process";
import { pathToFileURL } from "node:url";
import {
  CATALOG_SOURCE_PATH, CATALOG_PROJECTION_PATH,
  renderBorgAssemblyRecordCatalog, buildBorgAssemblyRecordCatalog,
} from "../scripts/borg/build-assembly-record-catalog.mjs";
import {
  parseBorgAssemblyRecordCatalogData, validateBorgAssemblyRecordCatalogData,
} from "../src/apps/borg/BorgAssemblyRecordCatalogContract.js";

const root = path.resolve(import.meta.dirname, "..");
const known = () => ({ schema: "borg-assembly-record-catalog.v2", entries: [{
  assemblyId: `asm-${"1".repeat(32)}`, modelRevisionSha256: "1".repeat(64),
  label: 'Literal "quoted" navigation', recordUrl: "content/assets/borg/records/known.v0.json",
}] });

test("known data-only projection preserves literal values and has no module dependencies", async () => {
  const data = known();
  const rendered = renderBorgAssemblyRecordCatalog(JSON.stringify(data));
  assert.equal(rendered, renderBorgAssemblyRecordCatalog(JSON.stringify(data, null, 2)));
  assert.match(rendered, /^\/\/ Generated by/);
  const literal = rendered.slice(rendered.indexOf("export default ") + "export default ".length, -2);
  assert.deepEqual(JSON.parse(literal), data);
  assert.deepEqual((await import(`data:text/javascript,${encodeURIComponent(rendered)}`)).default, data);
});

test("catalog data rejects malformed schema, identities, URLs, duplicate rows and JSON keys", () => {
  assert.deepEqual(parseBorgAssemblyRecordCatalogData(JSON.stringify(known())), known());
  for (const change of [
    (d) => { d.schema = "unknown"; }, (d) => { d.extra = true; },
    (d) => { d.entries = []; }, (d) => { d.entries = null; },
    (d) => { d.entries[0].label = " "; }, (d) => { d.entries[0].alias = "alias"; },
    (d) => { d.entries[0].modelRevisionSha256 = "invalid"; },
    (d) => { d.entries[0].assemblyId = `asm-${"2".repeat(32)}`; },
    (d) => { d.entries.push({ ...d.entries[0] }); },
    (d) => { d.entries.push({ ...d.entries[0], assemblyId: `asm-${"2".repeat(32)}`, modelRevisionSha256: "2".repeat(64) }); },
  ]) {
    const data = known(); change(data);
    assert.throws(() => renderBorgAssemblyRecordCatalog(JSON.stringify(data)), TypeError);
  }
  for (const url of ["https://example.com/a.json", "content/assets/borg/records/../a.json",
    "content/assets/borg/records/./a.json", "content/assets/borg/records/%61.json",
    "content/assets/borg/records/a.json?x=1", "content/assets/borg/records/a.json#part",
    "content/assets/borg/records//a.json", "content/assets/borg/records/a\\b.json"]) {
    const data = known(); data.entries[0].recordUrl = url;
    assert.throws(() => validateBorgAssemblyRecordCatalogData(data), /canonical local/);
  }
  const raw = JSON.stringify(known());
  assert.throws(() => renderBorgAssemblyRecordCatalog(raw.replace('"schema":', '"schema":"hidden","schema":')), /Duplicate/);
  assert.throws(() => renderBorgAssemblyRecordCatalog(raw.replace('"label":', '"label":"hidden","la\\u0062el":')), /Duplicate/);
  assert.throws(() => renderBorgAssemblyRecordCatalog(raw + " trailing"), SyntaxError);
});

function fixture(t) {
  fs.mkdirSync(path.join(root, ".tmp/option-b-borg-catalog"), { recursive: true });
  const dir = fs.mkdtempSync(path.join(root, ".tmp/option-b-borg-catalog/test-"));
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }));
  const source = path.join(dir, CATALOG_SOURCE_PATH);
  const projection = path.join(dir, CATALOG_PROJECTION_PATH);
  fs.mkdirSync(path.dirname(source), { recursive: true });
  fs.writeFileSync(source, JSON.stringify(known()));
  return { dir, source, projection };
}

test("generator bootstraps missing projection; check is read-only and write is deterministic/idempotent", (t) => {
  const f = fixture(t);
  assert.throws(() => buildBorgAssemblyRecordCatalog({ rootDir: f.dir }), /missing or stale/);
  assert.equal(fs.existsSync(f.projection), false);
  assert.equal(buildBorgAssemblyRecordCatalog({ rootDir: f.dir, mode: "write" }).status, "written");
  const stat = fs.statSync(f.projection, { bigint: true });
  const bytes = fs.readFileSync(f.projection);
  assert.equal(buildBorgAssemblyRecordCatalog({ rootDir: f.dir }).status, "current");
  assert.equal(buildBorgAssemblyRecordCatalog({ rootDir: f.dir, mode: "write" }).status, "current");
  assert.equal(fs.statSync(f.projection, { bigint: true }).mtimeNs, stat.mtimeNs);
  assert.deepEqual(fs.readFileSync(f.projection), bytes);
  fs.appendFileSync(f.projection, "// drift\n");
  assert.throws(() => buildBorgAssemblyRecordCatalog({ rootDir: f.dir }), /missing or stale/);
  assert.equal(buildBorgAssemblyRecordCatalog({ rootDir: f.dir, mode: "write" }).status, "written");
  assert.deepEqual(fs.readFileSync(f.projection), bytes);
  const data = known(); data.entries[0].label = "Changed canonical label";
  fs.writeFileSync(f.source, JSON.stringify(data));
  assert.throws(() => buildBorgAssemblyRecordCatalog({ rootDir: f.dir }), /missing or stale/);
  assert.deepEqual(fs.readFileSync(f.projection), bytes);
  fs.writeFileSync(f.source, "{}");
  assert.throws(() => buildBorgAssemblyRecordCatalog({ rootDir: f.dir, mode: "write" }), /schema/);
  assert.deepEqual(fs.readFileSync(f.projection), bytes);
});

test("generator rejects invalid UTF-8 and symbolic source/output paths", (t) => {
  const f = fixture(t);
  fs.writeFileSync(f.source, Buffer.from([0xff]));
  assert.throws(() => buildBorgAssemblyRecordCatalog({ rootDir: f.dir, mode: "write" }), /encoded data/);
  fs.writeFileSync(f.source, JSON.stringify(known()));
  buildBorgAssemblyRecordCatalog({ rootDir: f.dir, mode: "write" });
  fs.renameSync(f.projection, f.projection + ".saved");
  fs.symlinkSync(f.projection + ".saved", f.projection);
  assert.throws(() => buildBorgAssemblyRecordCatalog({ rootDir: f.dir }), /canonical regular/);
  fs.renameSync(f.source, f.source + ".saved");
  fs.symlinkSync(f.source + ".saved", f.source);
  assert.throws(() => buildBorgAssemblyRecordCatalog({ rootDir: f.dir }), /canonical regular/);
});

test("generator rejects identical-byte file and parent-directory replacements during capture", (t) => {
  for (const replaceDirectory of [false, true]) {
    const f = fixture(t);
    buildBorgAssemblyRecordCatalog({ rootDir: f.dir, mode: "write" });
    assert.equal(buildBorgAssemblyRecordCatalog({ rootDir: f.dir }).status, "current");
    const originalRead = fs.readFileSync;
    let replaced = false;
    const mocked = t.mock.method(fs, "readFileSync", function (target, ...args) {
      const result = originalRead.call(fs, target, ...args);
      if (!replaced && typeof target === "number") {
        replaced = true;
        if (replaceDirectory) {
          fs.renameSync(path.dirname(f.source), path.dirname(f.source) + ".saved");
          fs.mkdirSync(path.dirname(f.source));
          fs.copyFileSync(path.join(path.dirname(f.source) + ".saved", path.basename(f.source)), f.source);
        } else {
          fs.copyFileSync(f.source, f.source + ".replacement");
          fs.renameSync(f.source + ".replacement", f.source);
        }
      }
      return result;
    });
    try {
      assert.throws(() => buildBorgAssemblyRecordCatalog({ rootDir: f.dir, mode: "write" }), /source changed/);
      assert.equal(replaced, true);
    } finally { mocked.mock.restore(); }
  }
});

test("plain catalog ESM is synchronous, immutable, fetch-free and fails closed without its projection", (t) => {
  const f = fixture(t);
  for (const filename of ["BorgAssemblyRecordCatalog.js", "BorgAssemblyRecordCatalogContract.js"]) {
    fs.copyFileSync(path.join(root, "src/apps/borg", filename), path.join(f.dir, "src/apps/borg", filename));
  }
  const moduleUrl = pathToFileURL(path.join(f.dir, "src/apps/borg/BorgAssemblyRecordCatalog.js")).href;
  const code = `import assert from 'node:assert/strict';
    globalThis.fetch = () => { throw Error('unexpected fetch'); };
    const m = await import(${JSON.stringify(moduleUrl)});
    assert.deepEqual(Object.keys(m).sort(), ['BORG_ASSEMBLY_RECORD_CATALOG', 'BORG_ASSEMBLY_RECORD_CATALOG_ID', 'borgAssemblyRecordLabel', 'createBorgAssemblyRecordCatalog'].sort());
    const c = m.BORG_ASSEMBLY_RECORD_CATALOG;
    assert.equal(c.then, undefined);
    assert.ok(Object.isFrozen(c) && Object.isFrozen(c.entries) && Object.isFrozen(c.entries[0]));
    assert.throws(() => { c.entries[0].label = 'changed'; }, TypeError);
    assert.throws(() => c.entries.push(c.entries[0]), TypeError);
    assert.equal(m.borgAssemblyRecordLabel(c.entries[0].assemblyId), c.entries[0].label);
    assert.equal(m.borgAssemblyRecordLabel(c.entries[0].assemblyId, 'wrong'), null);
    const input = [{ ...c.entries[0] }]; const custom = m.createBorgAssemblyRecordCatalog(input);
    input[0].label = 'changed'; assert.notEqual(custom.entries[0].label, input[0].label);`;
  const missing = spawnSync(process.execPath, ["--input-type=module", "-e", code], { encoding: "utf8", timeout: 10_000 });
  assert.notEqual(missing.status, 0);
  assert.match(missing.stderr, /ERR_MODULE_NOT_FOUND/);
  buildBorgAssemblyRecordCatalog({ rootDir: f.dir, mode: "write" });
  execFileSync(process.execPath, ["--input-type=module", "-e", code], { timeout: 10_000 });
});

test("repository projection exactly follows authored JSON and plain ESM needs no JSON loader", async () => {
  const source = fs.readFileSync(path.join(root, CATALOG_SOURCE_PATH), "utf8");
  const projected = fs.readFileSync(path.join(root, CATALOG_PROJECTION_PATH), "utf8");
  assert.equal(projected, renderBorgAssemblyRecordCatalog(source));
  assert.deepEqual((await import(pathToFileURL(path.join(root, CATALOG_PROJECTION_PATH)))).default, JSON.parse(source));
  execFileSync(process.execPath, ["--check", path.join(root, CATALOG_PROJECTION_PATH)], { timeout: 10_000 });
  assert.equal(buildBorgAssemblyRecordCatalog().status, "current");
});
