import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,realpathSync,rmSync,writeFileSync} from 'node:fs';import {tmpdir} from 'node:os';import path from 'node:path';
import {captureCircularFile} from '../src/prescribed-path-analysis/SubfieldCircularObservationOwner.mjs';
import {createCircularMemoryOwner} from '../src/prescribed-path-analysis/SubfieldCircularMemoryOwner.mjs';
const hostTest = (name, fn) => test(name, {skip: process.platform !== 'darwin' && 'Actual observation requires the reviewed macOS shared-venv runtime'}, fn);
const root=process.cwd(),python=path.resolve(process.env.AAA_VENV??'../.venv','bin/python'),original=path.join(root,'scripts/eom/observe-subfield-circular-memory.py');
const policy={minimumSystemFreePercent:0,minimumFreeDiskBytesAtLaunch:0,minimumFreeDiskBytesDuringRun:0};
function fixture(injection='',transform=value=>value) {const dir=realpathSync(mkdtempSync(path.join(tmpdir(),'memory-owner-control-'))),helper=path.join(dir,'helper.py');let source=readFileSync(original,'utf8');const anchor='    duration = plan["durationMs"] / 1000';assert.equal(source.split(anchor).length,2);writeFileSync(helper,transform(source.replace(anchor,injection+anchor)));const controller=new AbortController();return{dir,helper,controller,owner:createCircularMemoryOwner({capture:captureCircularFile,python,helper,sources:[captureCircularFile(helper)],root,completionEnd:performance.now()+15000,signal:controller.signal,maximumProbeMs:500})};}
hostTest('known memory percentage and threshold boundary precede actual utility controls',async()=>{const transform=source=>source.replace('["/usr/bin/memory_pressure"]','["/bin/echo", "System-wide memory free percentage: 65%"]');const f=fixture('',transform);try{await f.owner.initialize();const value=await f.owner.observe({policy:{...policy,minimumSystemFreePercent:65}});assert.equal(value.freePercent,65);await f.owner.finish();}finally{rmSync(f.dir,{recursive:true});}const g=fixture('',transform);try{await g.owner.initialize();await assert.rejects(g.owner.observe({policy:{...policy,minimumSystemFreePercent:66}}),/below/);}finally{rmSync(g.dir,{recursive:true});}});
hostTest('known helper failure rejects before actual utility controls',async()=>{
 const f=fixture('    if plan.get("mode") == "memory":\n        raise ValueError("known rejected control")\n');try{await f.owner.initialize();await assert.rejects(f.owner.observe({policy}),/failed/);assert.equal(f.owner.snapshot().probes.at(-1).closed,true);}finally{rmSync(f.dir,{recursive:true});}
});
hostTest('actual memory query binds libpython and observes wait4 plus stream closure',async()=>{const f=fixture();try{const initial=await f.owner.initialize();assert(initial.runtime.some(row=>/\/Python\.framework\/.*\/Python$/u.test(row.path)));const value=await f.owner.observe({policy});assert(value.freePercent>=0&&value.freePercent<=100);const done=await f.owner.finish();assert(done.closed);assert(done.probes.at(-1).queryClosed);assert(done.probes.at(-1).queryResourceUsage.maximumResidentBytes>0);}finally{rmSync(f.dir,{recursive:true});}});
for(const [name,code]of [['stubborn','signal.signal(signal.SIGTERM,signal.SIG_IGN); time.sleep(5)'],['growth','sys.stdout.write("x"*(4*1024*1024));sys.stdout.flush()']])hostTest(name+' memory helper rejects after actual closure',async()=>{const f=fixture(`    if plan.get("mode") == "memory": ${code}\n`);try{await f.owner.initialize();await assert.rejects(f.owner.observe({policy}),/failed/);await assert.rejects(f.owner.finish());const last=f.owner.snapshot().probes.at(-1);assert(last.closed);assert(last.cpuUpperBoundSeconds>0);if(name==='stubborn')assert(last.escalated);if(name==='growth')assert(last.droppedBytes>0);}finally{rmSync(f.dir,{recursive:true});}});
hostTest('changed source and resource shortfall do not admit',async()=>{const f=fixture();try{await f.owner.initialize();await assert.rejects(f.owner.observe({policy:{...policy,minimumSystemFreePercent:101}}),/below/);await assert.rejects(f.owner.finish(),/below/);}finally{rmSync(f.dir,{recursive:true});}const g=fixture();try{await g.owner.initialize();writeFileSync(g.helper,'changed');await assert.rejects(g.owner.observe({policy}),/hash differs/);}finally{rmSync(g.dir,{recursive:true});}});
