import knownHashes from '../scripts/equation-mapping/fixtures/known-hash-answers.json' with { type: 'json' };
const ABC_SHA = knownHashes.sha256.abc;
import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {embedCircularPrior,decodeCircularPrior,buildCurrentCircularPriorPacket,finalizeCurrentCircularPrior} from '../scripts/eom/prepare-current-subfield-circular-prior.mjs';
const sha=data=>createHash('sha256').update(data).digest('hex'),record=(path,value)=>{const data=Buffer.from(JSON.stringify(value));return{path,sha256:sha(data),data};};
function known(previous=8){const candidateId='coincident-midpoint-common-frequency',planBinding={path:'/plan',sha256:'a'.repeat(64)},phases=Array.from({length:previous},(_,i)=>({path:`/phase-${previous}-${i}`,sha256:'b'.repeat(64)}));
 const probe={closed:true,exitObserved:true,exitCode:0,exitSignal:null},owner={closed:true,failure:null,probes:[probe,probe]},terminalProjection={runId:'known-run',exitCode:0,processGroupClosed:true,elapsedWallSeconds:1};
 const jointBinding=record('/joint',{schema:'circular-current-rung-admission.v1',accepted:true,h3EvidenceEligible:false,candidateId,rung:previous,process:{accepted:true,processesClosed:true,guardClosed:true,admission:{accepted:true,h3EvidenceEligible:false,candidateId,rung:previous,plan:planBinding,phaseReceipts:phases}},observations:owner,memory:owner});
 const earlierAdmissions=previous===8?[]:[record('/earlier',{known:'earlier captured packet'})];
 const priorPrefix=record('/prefix',{candidateId,phaseReceipts:Array.from({length:previous===8?2:10},(_,i)=>({path:`/old-${i}`,sha256:'c'.repeat(64)})),rungAdmissions:earlierAdmissions.map(({path,sha256})=>({path,sha256}))});
 const stdoutBinding=record('/stdout',{accepted:true,admission:{path:jointBinding.path,sha256:jointBinding.sha256}});
 const reviewBinding=record('/review',{schema:'circular-independent-current-rung-review.v1',accepted:true,h3EvidenceEligible:false,candidateId,rung:previous,phaseCount:previous,rowCount:previous*36,admission:{path:jointBinding.path,sha256:jointBinding.sha256},externalOwner:terminalProjection,bindings:[stdoutBinding,priorPrefix].map(({path,sha256})=>({path,sha256})),dispatcherRecomputedAdmission:{phaseReceipts:phases}});
 return{jointBinding,reviewBinding,stdoutBinding,terminalProjection,priorPrefix,earlierAdmissions,planBinding,entrySha256:'d'.repeat(64),memoryOwnerSha256:'e'.repeat(64),memoryHelperSha256:'f'.repeat(64)};
}
test('known lossless gzip bytes and SHA precede target preparation',()=>{const data=Buffer.from('abc');assert.equal(sha(data),ABC_SHA);const binding={path:'/known',data,sha256:sha(data)},embedded=embedCircularPrior(binding);assert.deepEqual(decodeCircularPrior(embedded),binding);assert.throws(()=>decodeCircularPrior({...embedded,sha256:'0'.repeat(64)}));});
for(const previous of [8,32])test(`known ${previous} prior produces complete ${previous===8?32:128} chain only after review`,()=>{const input=known(previous),packet=JSON.parse(buildCurrentCircularPriorPacket(input).reviewBytes);assert.equal(packet.accepted,false);assert.equal(packet.rung,previous===8?32:128);assert.deepEqual(packet.admission,JSON.parse(input.jointBinding.data).process.admission);assert.throws(()=>finalizeCurrentCircularPrior(record('/next-review',packet)));packet.accepted=true;const accepted=record('/next-review',packet),prior=JSON.parse(finalizeCurrentCircularPrior(accepted));assert.equal(prior.phaseReceipts.length,previous===8?10:42);assert.equal(prior.rungAdmissions.length,previous===8?1:2);assert.deepEqual(prior.rungAdmissions.at(-1),{path:accepted.path,sha256:accepted.sha256});});
test('wrong closure, evidence digest, secret projection, scope and projection reject',()=>{for(const mutate of [x=>x.terminalProjection.exitCode=1,x=>x.terminalProjection.control={token:'must-never-leave-lease'},x=>x.jointBinding.sha256='0'.repeat(64),x=>x.priorPrefix=record('/prefix',{candidateId:'wrong',phaseReceipts:[],rungAdmissions:[]})]){const input=known();mutate(input);assert.throws(()=>buildCurrentCircularPriorPacket(input));}const packet=JSON.parse(buildCurrentCircularPriorPacket(known()).reviewBytes);packet.accepted=true;packet.admission.rung=32;assert.throws(()=>finalizeCurrentCircularPrior(record('/accepted',packet)),/projection/);});
test('finalizer rejects changed embedded terminal and phase evidence and oversized review',()=>{for(const mutate of [p=>p.immutablePriorEvidence.terminalProjection.record.exitCode=1,p=>p.immutablePriorEvidence.terminalProjection.authenticatedByIndependentReviewSha256='0'.repeat(64),p=>p.admission.phaseReceipts.reverse(),p=>p.immutablePriorEvidence.joint.sha256='0'.repeat(64)]){const packet=JSON.parse(buildCurrentCircularPriorPacket(known()).reviewBytes);packet.accepted=true;mutate(packet);assert.throws(()=>finalizeCurrentCircularPrior(record('/accepted',packet)));}assert.throws(()=>finalizeCurrentCircularPrior({data:Buffer.alloc(2*1024**2+1)}),/cap/);});
