import { parseReactionNodeKey } from "./ReactionNodeKeyRuntime.js";
import {
  getReactionObjectConnectorPolicy,
  getReactionParticipantPlacementClass,
  isReactionObjectPlacementAllowed,
} from "./ReactionObjectRegistryRuntime.js";
import { buildReactionSurfaceValidation } from "./ReactionSurfaceValidationRuntime.js";

const REACTION_FLOW_SCHEMA = "reaction-flow/v1";
const DEFAULT_STAGE_ID = "stage_manual_authoring";
const DEFAULT_SOURCE_DOCUMENT_ID = "reaction_designer_session";
const SOLVER_REQUEST_SCHEMA = "solver-request/v1";

function normalizeText(value = "") {
  return String(value ?? "").trim();
}

function buildReactionFlowReview(review = {}) {
  const status = normalizeText(review?.status) === "accepted" ? "accepted" : "draft";
  const acceptedAt = normalizeText(review?.acceptedAt);
  if (status === "accepted" && acceptedAt) {
    return {
      status,
      acceptedAt,
    };
  }
  return {
    status: "draft",
  };
}

function normalizeParticipantSide(participant = {}) {
  const placementClass = getReactionParticipantPlacementClass(participant);
  if (placementClass === "product") {
    return "product";
  }
  if (placementClass === "reactant") {
    return "reactant";
  }
  return "intermediate";
}

function normalizeParticipantLayoutColumn(participant = {}) {
  const placementClass = getReactionParticipantPlacementClass(participant);
  if (placementClass === "product") {
    return "right";
  }
  if (placementClass === "center") {
    return "center";
  }
  return "left";
}

function buildTagList(values = []) {
  return [...new Set(values.map((value) => normalizeText(value)).filter(Boolean))];
}

function buildReactionFlowReviewInput(reviewInput = {}) {
  if (normalizeText(reviewInput?.schema) !== SOLVER_REQUEST_SCHEMA) {
    return null;
  }
  const requestId = normalizeText(reviewInput?.requestId);
  const sourceKind = normalizeText(reviewInput?.origin?.sourceKind);
  const sourceDocumentId = normalizeText(reviewInput?.origin?.sourceDocumentId);
  const title = normalizeText(reviewInput?.origin?.title);
  if (!requestId || !sourceKind || !sourceDocumentId) {
    return null;
  }
  const upstreamContext = reviewInput?.upstreamContext && typeof reviewInput.upstreamContext === "object"
    ? structuredClone(reviewInput.upstreamContext)
    : null;
  return {
    schema: SOLVER_REQUEST_SCHEMA,
    requestId,
    origin: Object.fromEntries(
      Object.entries({
        sourceKind,
        sourceDocumentId,
        title,
      }).filter(([, value]) => value !== "")
    ),
    ...(upstreamContext ? { upstreamContext } : {}),
  };
}

function buildParticipantTags(participant = {}) {
  return buildTagList([
    participant?.side === "reactant" && participant?.surfaceColumn !== "center-assembly"
      ? "incoming"
      : "",
    participant?.side === "product" ? "outgoing" : "",
    participant?.surfaceColumn === "center-assembly" ? "center-assembly" : "",
    participant?.isDissociatedComposite ? "manual-dissociated" : "",
    participant?.isAutoDissociatedComposite ? "auto-dissociated" : "",
    participant?.templateId ?? "",
    participant?.templateId === "upi0" || participant?.templateId === "dpi0" ? "pi0" : "",
    participant?.isSolveGenerated ? "solve-generated" : "",
    participant?.isAutoGeneratedDissociateAssembly ? "auto-generated" : "",
    ...(Array.isArray(participant?.tags) ? participant.tags : []),
  ]);
}

function buildOperatorTags(participant = {}) {
  return buildTagList([
    "operator",
    participant?.templateId ?? "",
    participant?.isSolveGenerated ? "solve-generated" : "",
    ...(Array.isArray(participant?.tags) ? participant.tags : []),
  ]);
}

function normalizeAnchorInstanceIndex(anchorInstanceIndex = null) {
  if (
    anchorInstanceIndex === null ||
    anchorInstanceIndex === undefined ||
    anchorInstanceIndex === ""
  ) {
    return null;
  }
  const normalized = Number(anchorInstanceIndex);
  return Number.isInteger(normalized) && normalized >= 0 ? normalized : null;
}

function buildParticipantRole(participant = {}, direction = "output") {
  const placementClass = getReactionParticipantPlacementClass(participant);
  const connectorPolicy = getReactionObjectConnectorPolicy(participant?.templateId, placementClass);
  if (direction === "input") {
    return normalizeText(connectorPolicy?.inputRole);
  }
  return normalizeText(connectorPolicy?.outputRole);
}

function getParticipantLaneNumber(participant = {}) {
  if (participant?.side === "operator") {
    return Math.max(0, Math.round(Number(participant?.operatorLaneIndex) || 0)) === 0 ? 2 : 4;
  }
  const placementClass = getReactionParticipantPlacementClass(participant);
  if (placementClass === "center") {
    return 3;
  }
  if (placementClass === "product") {
    return 5;
  }
  return 1;
}

function getExpectedSnapshotEndpointRole(participant = {}, direction = "output") {
  if (participant?.side === "operator") {
    return direction === "input" ? "operator-input" : "operator-output";
  }
  return buildParticipantRole(participant, direction);
}

function validateSnapshotEndpoint(participant = {}, mapping = {}, direction = "output") {
  const expectedRole = getExpectedSnapshotEndpointRole(participant, direction);
  const actualRole =
    direction === "input" ? normalizeText(mapping?.targetRole) : normalizeText(mapping?.sourceRole);
  const actualAnchorInstanceIndex = normalizeAnchorInstanceIndex(
    direction === "input" ? mapping?.targetAnchorInstanceIndex : mapping?.sourceAnchorInstanceIndex
  );
  if (!expectedRole) {
    throw new Error(
      `Reaction flow export cannot use ${direction} endpoint for ${String(participant?.id ?? "(missing participant)")} in lane ${getParticipantLaneNumber(participant)}.`
    );
  }
  if (actualRole !== expectedRole) {
    throw new Error(
      `Reaction flow export expected ${expectedRole} for ${String(participant?.id ?? "(missing participant)")} but got ${actualRole || "(missing role)"}.`
    );
  }
  if (participant?.side === "operator" && actualAnchorInstanceIndex !== 0) {
    throw new Error(
      `Reaction flow export requires operator anchorInstanceIndex 0 for ${String(participant?.id ?? "(missing participant)")}.`
    );
  }
  const placementClass = getReactionParticipantPlacementClass(participant);
  if (placementClass !== "center") {
    return;
  }
  if (direction === "input" && actualAnchorInstanceIndex !== 0) {
    throw new Error(
      `Reaction flow export requires center input anchorInstanceIndex 0 for ${String(participant?.id ?? "(missing participant)")}.`
    );
  }
  if (direction === "output") {
    if (normalizeText(participant?.templateId) === "free_architrinos") {
      if (actualAnchorInstanceIndex === null || actualAnchorInstanceIndex < 1) {
        throw new Error(
          `Reaction flow export requires free-architrinos output anchorInstanceIndex >= 1 for ${String(participant?.id ?? "(missing participant)")}.`
        );
      }
      return;
    }
    if (actualAnchorInstanceIndex !== 1) {
      throw new Error(
        `Reaction flow export requires center output anchorInstanceIndex 1 for ${String(participant?.id ?? "(missing participant)")}.`
      );
    }
  }
}

function validateSnapshotMapping(mapping = {}, participantsById = new Map()) {
  const sourceParticipantId = normalizeText(parseReactionNodeKey(mapping?.sourceKey).participantId);
  const targetParticipantId = normalizeText(parseReactionNodeKey(mapping?.targetKey).participantId);
  const sourceParticipant = participantsById.get(sourceParticipantId) ?? null;
  const targetParticipant = participantsById.get(targetParticipantId) ?? null;
  if (!sourceParticipant || !targetParticipant) {
    throw new Error(
      `Reaction flow export mapping ${String(mapping?.id ?? "(missing id)")} references unknown participant(s): ${sourceParticipantId || "(missing source)"} -> ${targetParticipantId || "(missing target)"}`
    );
  }
  validateSnapshotEndpoint(sourceParticipant, mapping, "output");
  validateSnapshotEndpoint(targetParticipant, mapping, "input");
}

function buildParticipantState(participant = {}) {
  const state = Object.fromEntries(
    Object.entries({
      dissociation: participant?.isDissociatedComposite
        ? "manual-dissociated"
        : participant?.isAutoDissociatedComposite
          ? "auto-dissociated"
          : undefined,
      solveGenerated: participant?.isSolveGenerated === true ? true : undefined,
      autoGenerated: participant?.isAutoGeneratedDissociateAssembly === true ? true : undefined,
    }).filter(([, value]) => value !== undefined)
  );
  return Object.keys(state).length ? state : undefined;
}

function buildEndpoint(nodeKey = "", role = "", anchorInstanceIndex = null) {
  const { participantId = "", nodeId = "" } = parseReactionNodeKey(nodeKey);
  const normalizedAnchorInstanceIndex = normalizeAnchorInstanceIndex(anchorInstanceIndex);
  return Object.fromEntries(Object.entries({
    participantId: String(participantId ?? "").trim(),
    anchorId: String(nodeId ?? "").trim() || "root",
    role: normalizeText(role),
    anchorInstanceIndex: normalizedAnchorInstanceIndex ?? undefined,
  }).filter(([, value]) => value !== undefined));
}

function getOperatorInputEndpoints(operatorId = "", mappings = []) {
  return mappings
    .filter((mapping) => {
      const { participantId } = parseReactionNodeKey(mapping?.targetKey);
      return (
        String(participantId ?? "") === String(operatorId ?? "") &&
        String(mapping?.targetRole ?? "") === "operator-input"
      );
    })
    .map((mapping) =>
      buildEndpoint(mapping.sourceKey, mapping?.sourceRole, mapping?.sourceAnchorInstanceIndex)
    )
    .filter((endpoint) => endpoint.participantId && endpoint.anchorId && endpoint.role);
}

function getOperatorOutputEndpoints(operatorId = "", mappings = []) {
  return mappings
    .filter((mapping) => {
      const { participantId } = parseReactionNodeKey(mapping?.sourceKey);
      return (
        String(participantId ?? "") === String(operatorId ?? "") &&
        String(mapping?.sourceRole ?? "") === "operator-output"
      );
    })
    .map((mapping) =>
      buildEndpoint(mapping.targetKey, mapping?.targetRole, mapping?.targetAnchorInstanceIndex)
    )
    .filter((endpoint) => endpoint.participantId && endpoint.anchorId && endpoint.role);
}

function buildViaOperatorId(mapping = {}, operatorIds = new Set()) {
  const targetParticipantId = String(parseReactionNodeKey(mapping?.targetKey).participantId ?? "").trim();
  if (String(mapping?.targetRole ?? "") === "operator-input" && operatorIds.has(targetParticipantId)) {
    return targetParticipantId;
  }
  const sourceParticipantId = String(parseReactionNodeKey(mapping?.sourceKey).participantId ?? "").trim();
  if (String(mapping?.sourceRole ?? "") === "operator-output" && operatorIds.has(sourceParticipantId)) {
    return sourceParticipantId;
  }
  return "";
}

export function buildReactionFlowDocument(options = {}) {
  const snapshot = options?.snapshot ?? {};
  const allParticipants = Array.isArray(snapshot?.participants) ? snapshot.participants : [];
  const mappings = Array.isArray(snapshot?.mappings) ? snapshot.mappings : [];
  const reviewInput = buildReactionFlowReviewInput(options?.reviewInput);
  const reactionId = normalizeText(options?.reactionId || "reaction_manual_draft") || "reaction_manual_draft";
  const title = normalizeText(options?.title || "Reaction Designer") || "Reaction Designer";
  const sourceDocumentIds = buildTagList(
    Array.isArray(options?.sourceDocumentIds) && options.sourceDocumentIds.length
      ? options.sourceDocumentIds
      : reviewInput?.origin?.sourceDocumentId
        ? [reviewInput.origin.sourceDocumentId]
        : [DEFAULT_SOURCE_DOCUMENT_ID]
  );
  const semanticTags = buildTagList(
    Array.isArray(options?.semanticTags) ? options.semanticTags : ["manual-authoring", "reaction-designer"]
  );
  const suggestedSceneId = normalizeText(options?.suggestedSceneId || `${reactionId}_scene`) || `${reactionId}_scene`;
  const review = buildReactionFlowReview(options?.review);

  const operatorParticipants = allParticipants.filter((participant) => participant?.side === "operator");
  const nonOperatorParticipants = allParticipants.filter((participant) => participant?.side !== "operator");
  const operatorIds = new Set(
    operatorParticipants.map((participant) => String(participant?.id ?? "").trim()).filter(Boolean)
  );
  const participantsById = new Map(
    allParticipants
      .filter((participant) => normalizeText(participant?.id))
      .map((participant) => [normalizeText(participant.id), participant])
  );

  nonOperatorParticipants.forEach((participant) => {
    if (!isReactionObjectPlacementAllowed(participant?.templateId, getReactionParticipantPlacementClass(participant))) {
      throw new Error(
        `Reaction flow export cannot place ${String(participant?.id ?? "(missing id)")} as ${getReactionParticipantPlacementClass(participant)} for ${String(participant?.templateId ?? "(missing template)")} .`
      );
    }
  });
  operatorParticipants.forEach((participant) => {
    if (!isReactionObjectPlacementAllowed(participant?.templateId, "operator")) {
      throw new Error(
        `Reaction flow export cannot place operator ${String(participant?.id ?? "(missing id)")} as operator for ${String(participant?.templateId ?? "(missing template)")}.`
      );
    }
  });
  mappings.forEach((mapping) => {
    validateSnapshotMapping(mapping, participantsById);
  });
  const surfaceValidation = buildReactionSurfaceValidation(snapshot);
  if (!surfaceValidation.valid && options?.allowIncompleteSnapshot !== true) {
    throw new Error(
      `Reaction flow export requires all visible required connectors to be connected. ${surfaceValidation.message || "Open required connectors remain on the surface."}`
    );
  }

  const documentParticipants = nonOperatorParticipants.map((participant) => ({
    id: normalizeText(participant?.id),
    side: normalizeParticipantSide(participant),
    label: normalizeText(participant?.label) || normalizeText(participant?.templateId) || "Participant",
    structureKey: normalizeText(participant?.templateId) || undefined,
    provenanceId: normalizeText(participant?.provenanceId) || `prov_${normalizeText(participant?.id)}`,
    tags: buildParticipantTags(participant),
    state: buildParticipantState(participant),
    layout: {
      column: normalizeParticipantLayoutColumn(participant),
      row: Math.max(0, Math.round(Number(participant?.surfaceRowIndex) || 0)),
    },
  })).map((participant) =>
    Object.fromEntries(Object.entries(participant).filter(([, value]) => value !== undefined))
  );

  const documentOperators = operatorParticipants.map((participant) => ({
    id: normalizeText(participant?.id),
    type: normalizeText(participant?.templateId || "operator") || "operator",
    label: normalizeText(participant?.label) || "Operator",
    layout: {
      lane: Math.max(0, Math.round(Number(participant?.operatorLaneIndex) || 0)),
      row: Math.max(0, Math.round(Number(participant?.surfaceRowIndex) || 0)),
      slot: Math.max(0, Math.round(Number(participant?.operatorSlotIndex) || 0)),
    },
    stageId: DEFAULT_STAGE_ID,
    inputs: getOperatorInputEndpoints(participant?.id, mappings),
    outputs: getOperatorOutputEndpoints(participant?.id, mappings),
    tags: buildOperatorTags(participant),
  }));

  const documentMappings = mappings
    .map((mapping) => {
      const from = buildEndpoint(
        mapping?.sourceKey,
        mapping?.sourceRole,
        mapping?.sourceAnchorInstanceIndex
      );
      const to = buildEndpoint(
        mapping?.targetKey,
        mapping?.targetRole,
        mapping?.targetAnchorInstanceIndex
      );
      if (!from.participantId || !from.anchorId || !from.role || !to.participantId || !to.anchorId || !to.role) {
        return null;
      }
      const viaOperatorId = buildViaOperatorId(mapping, operatorIds);
      return {
        id: normalizeText(mapping?.id),
        from,
        to,
        ...(viaOperatorId ? { viaOperatorId } : {}),
        stageId: DEFAULT_STAGE_ID,
      };
    })
    .filter(Boolean);

  return {
    schema: REACTION_FLOW_SCHEMA,
    reactionId,
    title,
    review,
    participants: documentParticipants,
    operators: documentOperators,
    mappings: documentMappings,
    stages: [
      {
        id: DEFAULT_STAGE_ID,
        label: "Manual Authoring",
        order: 0,
      },
    ],
    provenance: {
      sourceDocumentIds,
      participantIds: documentParticipants.map((participant) => participant.id),
      mappingIds: documentMappings.map((mapping) => mapping.id),
      ...(reviewInput ? { reviewInput } : {}),
    },
    hints: {
      initialFramingTargets: documentParticipants.slice(0, 3).map((participant) => participant.id),
      semanticTags,
      suggestedSceneId,
    },
  };
}

export function createReactionFlowExportRuntime(options = {}) {
  const getSnapshot =
    typeof options?.getSnapshot === "function"
      ? options.getSnapshot
      : () => ({ participants: [], mappings: [] });
  const getReview =
    typeof options?.getReview === "function"
      ? options.getReview
      : () => ({ status: "draft" });
  const getDocumentOptions =
    typeof options?.getDocumentOptions === "function"
      ? options.getDocumentOptions
      : () => ({});

  return {
    exportDocument(overrides = {}) {
      const dynamicOptions = getDocumentOptions();
      return buildReactionFlowDocument({
        ...options,
        ...dynamicOptions,
        ...overrides,
        snapshot: getSnapshot(),
        review: overrides?.review ?? getReview(),
      });
    },
  };
}
