import { parseReactionNodeKey } from "./ReactionNodeKeyRuntime.js";

const REACTION_FLOW_SCHEMA = "reaction-flow/v1";
const DEFAULT_STAGE_ID = "stage_manual_authoring";
const DEFAULT_SOURCE_DOCUMENT_ID = "reaction_designer_session";

function normalizeParticipantSide(participant = {}) {
  if (participant?.side === "product") {
    return "product";
  }
  if (participant?.side === "reactant" && participant?.surfaceColumn !== "center-assembly") {
    return "reactant";
  }
  return "intermediate";
}

function normalizeParticipantLayoutColumn(participant = {}) {
  if (participant?.side === "product") {
    return "right";
  }
  if (participant?.surfaceColumn === "center-assembly") {
    return "center";
  }
  return "left";
}

function buildTagList(values = []) {
  return [...new Set(values.map((value) => String(value ?? "").trim()).filter(Boolean))];
}

function buildParticipantTags(participant = {}) {
  return buildTagList([
    participant?.side === "reactant" && participant?.surfaceColumn !== "center-assembly"
      ? "incoming"
      : "",
    participant?.side === "product" ? "outgoing" : "",
    participant?.surfaceColumn === "center-assembly" ? "center-assembly" : "",
    participant?.templateId ?? "",
    participant?.templateId === "upi0" || participant?.templateId === "dpi0" ? "pi0" : "",
    participant?.isSolveGenerated ? "solve-generated" : "",
    participant?.isAutoGeneratedDissociateAssembly ? "auto-generated" : "",
  ]);
}

function buildOperatorTags(participant = {}) {
  return buildTagList([
    "operator",
    participant?.templateId ?? "",
    participant?.isSolveGenerated ? "solve-generated" : "",
  ]);
}

function buildEndpoint(nodeKey = "") {
  const { participantId = "", nodeId = "" } = parseReactionNodeKey(nodeKey);
  return {
    participantId: String(participantId ?? "").trim(),
    anchorId: String(nodeId ?? "").trim() || "root",
  };
}

function getOperatorInputEndpoints(operatorId = "", mappings = []) {
  return mappings
    .filter((mapping) => {
      const { participantId } = parseReactionNodeKey(mapping?.targetKey);
      return (
        String(participantId ?? "") === String(operatorId ?? "") &&
        String(mapping?.targetRole ?? "") === "operator-input"
      );
    })
    .map((mapping) => buildEndpoint(mapping.sourceKey))
    .filter((endpoint) => endpoint.participantId && endpoint.anchorId);
}

function getOperatorOutputEndpoints(operatorId = "", mappings = []) {
  return mappings
    .filter((mapping) => {
      const { participantId } = parseReactionNodeKey(mapping?.sourceKey);
      return (
        String(participantId ?? "") === String(operatorId ?? "") &&
        String(mapping?.sourceRole ?? "") === "operator-output"
      );
    })
    .map((mapping) => buildEndpoint(mapping.targetKey))
    .filter((endpoint) => endpoint.participantId && endpoint.anchorId);
}

function buildViaOperatorId(mapping = {}, operatorIds = new Set()) {
  const targetParticipantId = String(parseReactionNodeKey(mapping?.targetKey).participantId ?? "").trim();
  if (String(mapping?.targetRole ?? "") === "operator-input" && operatorIds.has(targetParticipantId)) {
    return targetParticipantId;
  }
  const sourceParticipantId = String(parseReactionNodeKey(mapping?.sourceKey).participantId ?? "").trim();
  if (String(mapping?.sourceRole ?? "") === "operator-output" && operatorIds.has(sourceParticipantId)) {
    return sourceParticipantId;
  }
  return "";
}

export function buildReactionFlowDocument(options = {}) {
  const snapshot = options?.snapshot ?? {};
  const allParticipants = Array.isArray(snapshot?.participants) ? snapshot.participants : [];
  const mappings = Array.isArray(snapshot?.mappings) ? snapshot.mappings : [];
  const reactionId = String(options?.reactionId ?? "reaction_manual_draft").trim() || "reaction_manual_draft";
  const title =
    String(options?.title ?? "Reaction Designer").trim() || "Reaction Designer";
  const sourceDocumentIds = Array.isArray(options?.sourceDocumentIds) && options.sourceDocumentIds.length
    ? options.sourceDocumentIds
    : [DEFAULT_SOURCE_DOCUMENT_ID];
  const semanticTags = buildTagList(
    Array.isArray(options?.semanticTags) ? options.semanticTags : ["manual-authoring", "reaction-designer"]
  );
  const suggestedSceneId =
    String(options?.suggestedSceneId ?? `${reactionId}_scene`).trim() || `${reactionId}_scene`;

  const operatorParticipants = allParticipants.filter((participant) => participant?.side === "operator");
  const nonOperatorParticipants = allParticipants.filter((participant) => participant?.side !== "operator");
  const operatorIds = new Set(
    operatorParticipants.map((participant) => String(participant?.id ?? "").trim()).filter(Boolean)
  );

  const documentParticipants = nonOperatorParticipants.map((participant) => ({
    id: String(participant?.id ?? "").trim(),
    side: normalizeParticipantSide(participant),
    label: String(participant?.label ?? "").trim() || String(participant?.templateId ?? "Participant"),
    structureKey: String(participant?.templateId ?? "").trim() || undefined,
    provenanceId: `prov_${String(participant?.id ?? "").trim()}`,
    tags: buildParticipantTags(participant),
    layout: {
      column: normalizeParticipantLayoutColumn(participant),
      row: Math.max(0, Math.round(Number(participant?.surfaceRowIndex) || 0)),
    },
  })).map((participant) =>
    Object.fromEntries(Object.entries(participant).filter(([, value]) => value !== undefined))
  );

  const documentOperators = operatorParticipants.map((participant) => ({
    id: String(participant?.id ?? "").trim(),
    type: String(participant?.templateId ?? "operator").trim() || "operator",
    label: String(participant?.label ?? "").trim() || "Operator",
    stageId: DEFAULT_STAGE_ID,
    inputs: getOperatorInputEndpoints(participant?.id, mappings),
    outputs: getOperatorOutputEndpoints(participant?.id, mappings),
    tags: buildOperatorTags(participant),
  }));

  const documentMappings = mappings
    .map((mapping) => {
      const from = buildEndpoint(mapping?.sourceKey);
      const to = buildEndpoint(mapping?.targetKey);
      if (!from.participantId || !from.anchorId || !to.participantId || !to.anchorId) {
        return null;
      }
      const viaOperatorId = buildViaOperatorId(mapping, operatorIds);
      return {
        id: String(mapping?.id ?? "").trim(),
        from,
        to,
        ...(viaOperatorId ? { viaOperatorId } : {}),
        stageId: DEFAULT_STAGE_ID,
      };
    })
    .filter(Boolean);

  return {
    schema: REACTION_FLOW_SCHEMA,
    reactionId,
    title,
    participants: documentParticipants,
    operators: documentOperators,
    mappings: documentMappings,
    stages: [
      {
        id: DEFAULT_STAGE_ID,
        label: "Manual Authoring",
        order: 0,
      },
    ],
    provenance: {
      sourceDocumentIds,
      participantIds: documentParticipants.map((participant) => participant.id),
      mappingIds: documentMappings.map((mapping) => mapping.id),
    },
    hints: {
      initialFramingTargets: documentParticipants.slice(0, 3).map((participant) => participant.id),
      semanticTags,
      suggestedSceneId,
    },
  };
}

export function createReactionFlowExportRuntime(options = {}) {
  const getSnapshot =
    typeof options?.getSnapshot === "function"
      ? options.getSnapshot
      : () => ({ participants: [], mappings: [] });

  return {
    exportDocument(overrides = {}) {
      return buildReactionFlowDocument({
        ...options,
        ...overrides,
        snapshot: getSnapshot(),
      });
    },
  };
}
