from __future__ import annotations

import re

from scripts.pdg.pdgfeed_model import ParticleMapping, RequestOccurrenceTemplate


def _occurrence(assembly_id: str, title: str) -> RequestOccurrenceTemplate:
    return RequestOccurrenceTemplate(assembly_id=assembly_id, title=title)


def _mapping(
    *,
    canonical_name: str,
    canonical_id: str,
    full_name: str,
    aaa_notation: str,
    particle_type: str,
    family: str,
    generation: str,
    polarity: str,
    electrino_count: int,
    positrino_count: int,
    aliases: tuple[str, ...] = (),
    request_translation: str = "none",
    request_occurrences: tuple[RequestOccurrenceTemplate, ...] = (),
) -> ParticleMapping:
    return ParticleMapping(
        canonical_name=canonical_name,
        canonical_id=canonical_id,
        full_name=full_name,
        aaa_notation=aaa_notation,
        particle_type=particle_type,
        family=family,
        generation=generation,
        polarity=polarity,
        electrino_count=electrino_count,
        positrino_count=positrino_count,
        template_id=canonical_id,
        aliases=(canonical_name, *aliases),
        request_translation=request_translation,
        request_occurrences=request_occurrences,
    )


PDG_PARTICLE_MAPPINGS: tuple[ParticleMapping, ...] = (
    _mapping(
        canonical_name="h",
        canonical_id="pro_noether_core_I",
        full_name="Pro Noether Core",
        aaa_notation="h",
        particle_type="assembly",
        family="Noether core",
        generation="I",
        polarity="pro",
        electrino_count=3,
        positrino_count=3,
        request_translation="direct",
        request_occurrences=(_occurrence("pro_noether_core_I", "Pro Noether Core"),),
    ),
    _mapping(
        canonical_name="ah",
        canonical_id="anti_noether_core_I",
        full_name="Anti Noether Core",
        aaa_notation="ah",
        particle_type="assembly",
        family="Noether core",
        generation="I",
        polarity="anti",
        electrino_count=3,
        positrino_count=3,
        request_translation="direct",
        request_occurrences=(_occurrence("anti_noether_core_I", "Anti Noether Core"),),
    ),
    _mapping(
        canonical_name="h2",
        canonical_id="pro_noether_core_II",
        full_name="Pro Bi-Binary",
        aaa_notation="h2",
        particle_type="assembly",
        family="Noether core",
        generation="II",
        polarity="pro",
        electrino_count=2,
        positrino_count=2,
        request_translation="direct",
        request_occurrences=(_occurrence("pro_noether_core_II", "Pro Bi-Binary"),),
    ),
    _mapping(
        canonical_name="ah2",
        canonical_id="anti_noether_core_II",
        full_name="Anti Bi-Binary",
        aaa_notation="ah2",
        particle_type="assembly",
        family="Noether core",
        generation="II",
        polarity="anti",
        electrino_count=2,
        positrino_count=2,
        request_translation="direct",
        request_occurrences=(_occurrence("anti_noether_core_II", "Anti Bi-Binary"),),
    ),
    _mapping(
        canonical_name="h3",
        canonical_id="pro_noether_core_III",
        full_name="Pro Uni-Binary",
        aaa_notation="h3",
        particle_type="assembly",
        family="Noether core",
        generation="III",
        polarity="pro",
        electrino_count=1,
        positrino_count=1,
        request_translation="direct",
        request_occurrences=(_occurrence("pro_noether_core_III", "Pro Uni-Binary"),),
    ),
    _mapping(
        canonical_name="ah3",
        canonical_id="anti_noether_core_III",
        full_name="Anti Uni-Binary",
        aaa_notation="ah3",
        particle_type="assembly",
        family="Noether core",
        generation="III",
        polarity="anti",
        electrino_count=1,
        positrino_count=1,
        request_translation="direct",
        request_occurrences=(_occurrence("anti_noether_core_III", "Anti Uni-Binary"),),
    ),
    _mapping(
        canonical_name="e-",
        canonical_id="pro_electron_I",
        full_name="Electron",
        aaa_notation="e",
        particle_type="assembly",
        family="charged lepton",
        generation="I",
        polarity="pro",
        electrino_count=9,
        positrino_count=3,
        aliases=("electron",),
        request_translation="direct",
        request_occurrences=(_occurrence("pro_electron_I", "Electron"),),
    ),
    _mapping(
        canonical_name="e+",
        canonical_id="anti_electron_I",
        full_name="Positron",
        aaa_notation="ae",
        particle_type="assembly",
        family="charged lepton",
        generation="I",
        polarity="anti",
        electrino_count=3,
        positrino_count=9,
        aliases=("positron", "anti-electron"),
        request_translation="direct",
        request_occurrences=(_occurrence("anti_electron_I", "Positron"),),
    ),
    _mapping(
        canonical_name="nu_e",
        canonical_id="pro_electron_neutrino_I",
        full_name="Electron Neutrino",
        aaa_notation="v",
        particle_type="assembly",
        family="neutrino",
        generation="I",
        polarity="pro",
        electrino_count=6,
        positrino_count=6,
        aliases=("electron-neutrino",),
        request_translation="direct",
        request_occurrences=(_occurrence("pro_electron_neutrino_I", "Electron Neutrino"),),
    ),
    _mapping(
        canonical_name="anti-nu_e",
        canonical_id="anti_electron_neutrino_I",
        full_name="Anti Electron Neutrino",
        aaa_notation="av",
        particle_type="assembly",
        family="neutrino",
        generation="I",
        polarity="anti",
        electrino_count=6,
        positrino_count=6,
        aliases=("nubar_e", "anti-electron-neutrino"),
        request_translation="direct",
        request_occurrences=(_occurrence("anti_electron_neutrino_I", "Anti Electron Neutrino"),),
    ),
    _mapping(
        canonical_name="u",
        canonical_id="pro_up_quark_I",
        full_name="Up Quark",
        aaa_notation="u",
        particle_type="assembly",
        family="up-type quark",
        generation="I",
        polarity="pro",
        electrino_count=4,
        positrino_count=8,
        aliases=("up",),
        request_translation="direct",
        request_occurrences=(_occurrence("pro_up_quark_I", "Up Quark"),),
    ),
    _mapping(
        canonical_name="anti-u",
        canonical_id="anti_up_quark_I",
        full_name="Anti Up Quark",
        aaa_notation="au",
        particle_type="assembly",
        family="up-type quark",
        generation="I",
        polarity="anti",
        electrino_count=8,
        positrino_count=4,
        aliases=("antiup", "anti-up"),
        request_translation="direct",
        request_occurrences=(_occurrence("anti_up_quark_I", "Anti Up Quark"),),
    ),
    _mapping(
        canonical_name="d",
        canonical_id="pro_down_quark_I",
        full_name="Down Quark",
        aaa_notation="d",
        particle_type="assembly",
        family="down-type quark",
        generation="I",
        polarity="pro",
        electrino_count=7,
        positrino_count=5,
        aliases=("down",),
        request_translation="direct",
        request_occurrences=(_occurrence("pro_down_quark_I", "Down Quark"),),
    ),
    _mapping(
        canonical_name="anti-d",
        canonical_id="anti_down_quark_I",
        full_name="Anti Down Quark",
        aaa_notation="ad",
        particle_type="assembly",
        family="down-type quark",
        generation="I",
        polarity="anti",
        electrino_count=5,
        positrino_count=7,
        aliases=("antidown", "anti-down"),
        request_translation="direct",
        request_occurrences=(_occurrence("anti_down_quark_I", "Anti Down Quark"),),
    ),
    _mapping(
        canonical_name="mu-",
        canonical_id="pro_muon_II",
        full_name="Muon",
        aaa_notation="e2",
        particle_type="assembly",
        family="charged lepton",
        generation="II",
        polarity="pro",
        electrino_count=8,
        positrino_count=2,
        aliases=("muon",),
        request_translation="direct",
        request_occurrences=(_occurrence("pro_muon_II", "Muon"),),
    ),
    _mapping(
        canonical_name="mu+",
        canonical_id="anti_muon_II",
        full_name="Anti Muon",
        aaa_notation="ae2",
        particle_type="assembly",
        family="charged lepton",
        generation="II",
        polarity="anti",
        electrino_count=2,
        positrino_count=8,
        aliases=("anti-muon",),
        request_translation="direct",
        request_occurrences=(_occurrence("anti_muon_II", "Anti Muon"),),
    ),
    _mapping(
        canonical_name="nu_mu",
        canonical_id="pro_muon_neutrino_II",
        full_name="Muon Neutrino",
        aaa_notation="v2",
        particle_type="assembly",
        family="neutrino",
        generation="II",
        polarity="pro",
        electrino_count=5,
        positrino_count=5,
        aliases=("muon-neutrino",),
        request_translation="direct",
        request_occurrences=(_occurrence("pro_muon_neutrino_II", "Muon Neutrino"),),
    ),
    _mapping(
        canonical_name="anti-nu_mu",
        canonical_id="anti_muon_neutrino_II",
        full_name="Anti Muon Neutrino",
        aaa_notation="av2",
        particle_type="assembly",
        family="neutrino",
        generation="II",
        polarity="anti",
        electrino_count=5,
        positrino_count=5,
        aliases=("nubar_mu", "anti-muon-neutrino"),
        request_translation="direct",
        request_occurrences=(_occurrence("anti_muon_neutrino_II", "Anti Muon Neutrino"),),
    ),
    _mapping(
        canonical_name="c",
        canonical_id="pro_charm_quark_II",
        full_name="Charm Quark",
        aaa_notation="u2",
        particle_type="assembly",
        family="up-type quark",
        generation="II",
        polarity="pro",
        electrino_count=3,
        positrino_count=7,
        aliases=("charm",),
        request_translation="direct",
        request_occurrences=(_occurrence("pro_charm_quark_II", "Charm Quark"),),
    ),
    _mapping(
        canonical_name="anti-c",
        canonical_id="anti_charm_quark_II",
        full_name="Anti Charm Quark",
        aaa_notation="au2",
        particle_type="assembly",
        family="up-type quark",
        generation="II",
        polarity="anti",
        electrino_count=7,
        positrino_count=3,
        aliases=("anti-charm",),
        request_translation="direct",
        request_occurrences=(_occurrence("anti_charm_quark_II", "Anti Charm Quark"),),
    ),
    _mapping(
        canonical_name="s",
        canonical_id="pro_strange_quark_II",
        full_name="Strange Quark",
        aaa_notation="d2",
        particle_type="assembly",
        family="down-type quark",
        generation="II",
        polarity="pro",
        electrino_count=6,
        positrino_count=4,
        aliases=("strange",),
        request_translation="direct",
        request_occurrences=(_occurrence("pro_strange_quark_II", "Strange Quark"),),
    ),
    _mapping(
        canonical_name="anti-s",
        canonical_id="anti_strange_quark_II",
        full_name="Anti Strange Quark",
        aaa_notation="ad2",
        particle_type="assembly",
        family="down-type quark",
        generation="II",
        polarity="anti",
        electrino_count=4,
        positrino_count=6,
        aliases=("anti-strange",),
        request_translation="direct",
        request_occurrences=(_occurrence("anti_strange_quark_II", "Anti Strange Quark"),),
    ),
    _mapping(
        canonical_name="tau-",
        canonical_id="pro_tau_III",
        full_name="Tau",
        aaa_notation="e3",
        particle_type="assembly",
        family="charged lepton",
        generation="III",
        polarity="pro",
        electrino_count=7,
        positrino_count=1,
        aliases=("tau",),
        request_translation="direct",
        request_occurrences=(_occurrence("pro_tau_III", "Tau"),),
    ),
    _mapping(
        canonical_name="tau+",
        canonical_id="anti_tau_III",
        full_name="Anti Tau",
        aaa_notation="ae3",
        particle_type="assembly",
        family="charged lepton",
        generation="III",
        polarity="anti",
        electrino_count=1,
        positrino_count=7,
        aliases=("anti-tau",),
        request_translation="direct",
        request_occurrences=(_occurrence("anti_tau_III", "Anti Tau"),),
    ),
    _mapping(
        canonical_name="nu_tau",
        canonical_id="pro_tau_neutrino_III",
        full_name="Tau Neutrino",
        aaa_notation="v3",
        particle_type="assembly",
        family="neutrino",
        generation="III",
        polarity="pro",
        electrino_count=4,
        positrino_count=4,
        aliases=("tau-neutrino",),
        request_translation="direct",
        request_occurrences=(_occurrence("pro_tau_neutrino_III", "Tau Neutrino"),),
    ),
    _mapping(
        canonical_name="anti-nu_tau",
        canonical_id="anti_tau_neutrino_III",
        full_name="Anti Tau Neutrino",
        aaa_notation="av3",
        particle_type="assembly",
        family="neutrino",
        generation="III",
        polarity="anti",
        electrino_count=4,
        positrino_count=4,
        aliases=("nubar_tau", "anti-tau-neutrino"),
        request_translation="direct",
        request_occurrences=(_occurrence("anti_tau_neutrino_III", "Anti Tau Neutrino"),),
    ),
    _mapping(
        canonical_name="t",
        canonical_id="pro_top_quark_III",
        full_name="Top Quark",
        aaa_notation="u3",
        particle_type="assembly",
        family="up-type quark",
        generation="III",
        polarity="pro",
        electrino_count=2,
        positrino_count=6,
        aliases=("top",),
        request_translation="direct",
        request_occurrences=(_occurrence("pro_top_quark_III", "Top Quark"),),
    ),
    _mapping(
        canonical_name="anti-t",
        canonical_id="anti_top_quark_III",
        full_name="Anti Top Quark",
        aaa_notation="au3",
        particle_type="assembly",
        family="up-type quark",
        generation="III",
        polarity="anti",
        electrino_count=6,
        positrino_count=2,
        aliases=("anti-top",),
        request_translation="direct",
        request_occurrences=(_occurrence("anti_top_quark_III", "Anti Top Quark"),),
    ),
    _mapping(
        canonical_name="b",
        canonical_id="pro_bottom_quark_III",
        full_name="Bottom Quark",
        aaa_notation="d3",
        particle_type="assembly",
        family="down-type quark",
        generation="III",
        polarity="pro",
        electrino_count=5,
        positrino_count=3,
        aliases=("bottom",),
        request_translation="direct",
        request_occurrences=(_occurrence("pro_bottom_quark_III", "Bottom Quark"),),
    ),
    _mapping(
        canonical_name="anti-b",
        canonical_id="anti_bottom_quark_III",
        full_name="Anti Bottom Quark",
        aaa_notation="ad3",
        particle_type="assembly",
        family="down-type quark",
        generation="III",
        polarity="anti",
        electrino_count=3,
        positrino_count=5,
        aliases=("anti-bottom",),
        request_translation="direct",
        request_occurrences=(_occurrence("anti_bottom_quark_III", "Anti Bottom Quark"),),
    ),
    _mapping(
        canonical_name="p",
        canonical_id="proton",
        full_name="Proton",
        aaa_notation="P",
        particle_type="composite",
        family="baryon",
        generation="I",
        polarity="pro",
        electrino_count=15,
        positrino_count=21,
        aliases=("proton",),
        request_translation="expanded",
        request_occurrences=(
            _occurrence("pro_up_quark_I", "Up Quark"),
            _occurrence("pro_up_quark_I", "Up Quark"),
            _occurrence("pro_down_quark_I", "Down Quark"),
        ),
    ),
    _mapping(
        canonical_name="anti-p",
        canonical_id="anti_proton",
        full_name="Anti Proton",
        aaa_notation="aP",
        particle_type="composite",
        family="baryon",
        generation="I",
        polarity="anti",
        electrino_count=21,
        positrino_count=15,
        aliases=("pbar", "anti-proton"),
        request_translation="expanded",
        request_occurrences=(
            _occurrence("anti_up_quark_I", "Anti Up Quark"),
            _occurrence("anti_up_quark_I", "Anti Up Quark"),
            _occurrence("anti_down_quark_I", "Anti Down Quark"),
        ),
    ),
    _mapping(
        canonical_name="n",
        canonical_id="neutron",
        full_name="Neutron",
        aaa_notation="N",
        particle_type="composite",
        family="baryon",
        generation="I",
        polarity="pro",
        electrino_count=18,
        positrino_count=18,
        aliases=("neutron",),
        request_translation="expanded",
        request_occurrences=(
            _occurrence("pro_down_quark_I", "Down Quark"),
            _occurrence("pro_up_quark_I", "Up Quark"),
            _occurrence("pro_down_quark_I", "Down Quark"),
        ),
    ),
    _mapping(
        canonical_name="anti-n",
        canonical_id="anti_neutron",
        full_name="Anti Neutron",
        aaa_notation="aN",
        particle_type="composite",
        family="baryon",
        generation="I",
        polarity="anti",
        electrino_count=18,
        positrino_count=18,
        aliases=("nbar", "anti-neutron"),
        request_translation="expanded",
        request_occurrences=(
            _occurrence("anti_up_quark_I", "Anti Up Quark"),
            _occurrence("anti_down_quark_I", "Anti Down Quark"),
            _occurrence("anti_down_quark_I", "Anti Down Quark"),
        ),
    ),
    _mapping(
        canonical_name="gamma",
        canonical_id="photon",
        full_name="Photon",
        aaa_notation="hp",
        particle_type="composite",
        family="boson",
        generation="n/a",
        polarity="self-conjugate",
        electrino_count=6,
        positrino_count=6,
        aliases=("photon",),
        request_translation="expanded",
        request_occurrences=(
            _occurrence("pro_noether_core_I", "Pro Noether Core"),
            _occurrence("anti_noether_core_I", "Anti Noether Core"),
        ),
    ),
    _mapping(
        canonical_name="H",
        canonical_id="higgs_cluster",
        full_name="Higgs Cluster",
        aaa_notation="hq",
        particle_type="composite",
        family="boson",
        generation="n/a",
        polarity="mixed",
        electrino_count=12,
        positrino_count=12,
        aliases=("higgs-cluster",),
    ),
    _mapping(
        canonical_name="W+",
        canonical_id="w_plus_corridor",
        full_name="W+ Boson",
        aaa_notation="W+",
        particle_type="composite",
        family="weak boson",
        generation="n/a",
        polarity="pro",
        electrino_count=3,
        positrino_count=9,
        aliases=("w+",),
    ),
    _mapping(
        canonical_name="W-",
        canonical_id="w_minus_corridor",
        full_name="W- Boson",
        aaa_notation="W-",
        particle_type="composite",
        family="weak boson",
        generation="n/a",
        polarity="anti",
        electrino_count=9,
        positrino_count=3,
        aliases=("w-",),
    ),
    _mapping(
        canonical_name="Z",
        canonical_id="z_corridor",
        full_name="Z Boson",
        aaa_notation="Z",
        particle_type="composite",
        family="weak boson",
        generation="n/a",
        polarity="self-conjugate",
        electrino_count=6,
        positrino_count=6,
        aliases=("z",),
    ),
    _mapping(
        canonical_name="eta",
        canonical_id="eta_meson",
        full_name="Eta Meson",
        aaa_notation="u.au.d.ad.d2.ad2",
        particle_type="composite",
        family="meson",
        generation="I+II",
        polarity="self-conjugate",
        electrino_count=34,
        positrino_count=34,
        aliases=("eta-meson",),
        request_translation="expanded",
        request_occurrences=(
            _occurrence("pro_up_quark_I", "Up Quark"),
            _occurrence("anti_up_quark_I", "Anti Up Quark"),
            _occurrence("pro_down_quark_I", "Down Quark"),
            _occurrence("anti_down_quark_I", "Anti Down Quark"),
            _occurrence("pro_strange_quark_II", "Strange Quark"),
            _occurrence("anti_strange_quark_II", "Anti Strange Quark"),
        ),
    ),
    _mapping(
        canonical_name="phi",
        canonical_id="phi_meson",
        full_name="Phi Meson",
        aaa_notation="d2.ad2",
        particle_type="composite",
        family="meson",
        generation="II",
        polarity="self-conjugate",
        electrino_count=10,
        positrino_count=10,
        aliases=("phi-meson",),
        request_translation="expanded",
        request_occurrences=(
            _occurrence("pro_strange_quark_II", "Strange Quark"),
            _occurrence("anti_strange_quark_II", "Anti Strange Quark"),
        ),
    ),
    _mapping(
        canonical_name="pi+",
        canonical_id="positive_pion",
        full_name="Positive Pion",
        aaa_notation="u.ad",
        particle_type="composite",
        family="meson",
        generation="I",
        polarity="mixed",
        electrino_count=9,
        positrino_count=15,
        aliases=("positive-pion",),
        request_translation="expanded",
        request_occurrences=(
            _occurrence("pro_up_quark_I", "Up Quark"),
            _occurrence("anti_down_quark_I", "Anti Down Quark"),
        ),
    ),
    _mapping(
        canonical_name="pi0",
        canonical_id="neutral_pion",
        full_name="Neutral Pion",
        aaa_notation="u.au.d.ad",
        particle_type="composite",
        family="meson",
        generation="I",
        polarity="self-conjugate",
        electrino_count=24,
        positrino_count=24,
        aliases=("neutral-pion",),
        request_translation="expanded",
        request_occurrences=(
            _occurrence("pro_up_quark_I", "Up Quark"),
            _occurrence("anti_up_quark_I", "Anti Up Quark"),
            _occurrence("pro_down_quark_I", "Down Quark"),
            _occurrence("anti_down_quark_I", "Anti Down Quark"),
        ),
    ),
    _mapping(
        canonical_name="pi-",
        canonical_id="negative_pion",
        full_name="Negative Pion",
        aaa_notation="d.au",
        particle_type="composite",
        family="meson",
        generation="I",
        polarity="mixed",
        electrino_count=15,
        positrino_count=9,
        aliases=("negative-pion",),
        request_translation="expanded",
        request_occurrences=(
            _occurrence("pro_down_quark_I", "Down Quark"),
            _occurrence("anti_up_quark_I", "Anti Up Quark"),
        ),
    ),
    _mapping(
        canonical_name="K+",
        canonical_id="positive_kaon",
        full_name="Positive Kaon",
        aaa_notation="u.ad2",
        particle_type="composite",
        family="meson",
        generation="I+II",
        polarity="mixed",
        electrino_count=8,
        positrino_count=14,
        aliases=("k+", "positive-kaon"),
        request_translation="expanded",
        request_occurrences=(
            _occurrence("pro_up_quark_I", "Up Quark"),
            _occurrence("anti_strange_quark_II", "Anti Strange Quark"),
        ),
    ),
    _mapping(
        canonical_name="K0",
        canonical_id="neutral_kaon",
        full_name="Neutral Kaon",
        aaa_notation="d.ad2",
        particle_type="composite",
        family="meson",
        generation="I+II",
        polarity="mixed",
        electrino_count=11,
        positrino_count=11,
        aliases=("k0", "neutral-kaon"),
        request_translation="expanded",
        request_occurrences=(
            _occurrence("pro_down_quark_I", "Down Quark"),
            _occurrence("anti_strange_quark_II", "Anti Strange Quark"),
        ),
    ),
    _mapping(
        canonical_name="K-",
        canonical_id="negative_kaon",
        full_name="Negative Kaon",
        aaa_notation="au.d2",
        particle_type="composite",
        family="meson",
        generation="I+II",
        polarity="mixed",
        electrino_count=14,
        positrino_count=8,
        aliases=("k-", "negative-kaon"),
        request_translation="expanded",
        request_occurrences=(
            _occurrence("anti_up_quark_I", "Anti Up Quark"),
            _occurrence("pro_strange_quark_II", "Strange Quark"),
        ),
    ),
    _mapping(
        canonical_name="anti-K0",
        canonical_id="anti_neutral_kaon",
        full_name="Anti Neutral Kaon",
        aaa_notation="ad.d2",
        particle_type="composite",
        family="meson",
        generation="I+II",
        polarity="mixed",
        electrino_count=11,
        positrino_count=11,
        aliases=("anti-k0", "Kbar0", "kbar0", "anti-kaon0"),
        request_translation="expanded",
        request_occurrences=(
            _occurrence("anti_down_quark_I", "Anti Down Quark"),
            _occurrence("pro_strange_quark_II", "Strange Quark"),
        ),
    ),
    _mapping(
        canonical_name="K0S",
        canonical_id="short_neutral_kaon",
        full_name="Short Neutral Kaon",
        aaa_notation="d.ad2.ad.d2",
        particle_type="composite",
        family="meson",
        generation="I+II",
        polarity="self-conjugate",
        electrino_count=22,
        positrino_count=22,
        aliases=("k0s", "KS0", "ks0", "short-neutral-kaon"),
        request_translation="expanded",
        request_occurrences=(
            _occurrence("pro_down_quark_I", "Down Quark"),
            _occurrence("anti_strange_quark_II", "Anti Strange Quark"),
            _occurrence("anti_down_quark_I", "Anti Down Quark"),
            _occurrence("pro_strange_quark_II", "Strange Quark"),
        ),
    ),
    _mapping(
        canonical_name="K0L",
        canonical_id="long_neutral_kaon",
        full_name="Long Neutral Kaon",
        aaa_notation="d.ad2.ad.d2",
        particle_type="composite",
        family="meson",
        generation="I+II",
        polarity="self-conjugate",
        electrino_count=22,
        positrino_count=22,
        aliases=("k0l", "KL0", "kl0", "long-neutral-kaon"),
        request_translation="expanded",
        request_occurrences=(
            _occurrence("pro_down_quark_I", "Down Quark"),
            _occurrence("anti_strange_quark_II", "Anti Strange Quark"),
            _occurrence("anti_down_quark_I", "Anti Down Quark"),
            _occurrence("pro_strange_quark_II", "Strange Quark"),
        ),
    ),
    _mapping(
        canonical_name="B+",
        canonical_id="positive_b_meson",
        full_name="Positive B Meson",
        aaa_notation="u.ad3",
        particle_type="composite",
        family="meson",
        generation="I+III",
        polarity="mixed",
        electrino_count=7,
        positrino_count=13,
        aliases=("b+", "positive-b-meson"),
        request_translation="expanded",
        request_occurrences=(
            _occurrence("pro_up_quark_I", "Up Quark"),
            _occurrence("anti_bottom_quark_III", "Anti Bottom Quark"),
        ),
    ),
    _mapping(
        canonical_name="B0",
        canonical_id="neutral_b_meson",
        full_name="Neutral B Meson",
        aaa_notation="d.ad3",
        particle_type="composite",
        family="meson",
        generation="I+III",
        polarity="mixed",
        electrino_count=10,
        positrino_count=10,
        aliases=("b0", "neutral-b-meson"),
        request_translation="expanded",
        request_occurrences=(
            _occurrence("pro_down_quark_I", "Down Quark"),
            _occurrence("anti_bottom_quark_III", "Anti Bottom Quark"),
        ),
    ),
    _mapping(
        canonical_name="B-",
        canonical_id="negative_b_meson",
        full_name="Negative B Meson",
        aaa_notation="au.d3",
        particle_type="composite",
        family="meson",
        generation="I+III",
        polarity="mixed",
        electrino_count=13,
        positrino_count=7,
        aliases=("b-", "negative-b-meson"),
        request_translation="expanded",
        request_occurrences=(
            _occurrence("anti_up_quark_I", "Anti Up Quark"),
            _occurrence("pro_bottom_quark_III", "Bottom Quark"),
        ),
    ),
    _mapping(
        canonical_name="anti-B0",
        canonical_id="anti_neutral_b_meson",
        full_name="Anti Neutral B Meson",
        aaa_notation="ad.d3",
        particle_type="composite",
        family="meson",
        generation="I+III",
        polarity="mixed",
        electrino_count=10,
        positrino_count=10,
        aliases=("anti-b0", "Bbar0", "bbar0", "anti-b-meson"),
        request_translation="expanded",
        request_occurrences=(
            _occurrence("anti_down_quark_I", "Anti Down Quark"),
            _occurrence("pro_bottom_quark_III", "Bottom Quark"),
        ),
    ),
)


PARTICLE_CHARGE_THIRDS: dict[str, int] = {
    "h": 0,
    "ah": 0,
    "h2": 0,
    "ah2": 0,
    "h3": 0,
    "ah3": 0,
    "e-": -3,
    "e+": 3,
    "nu_e": 0,
    "anti-nu_e": 0,
    "u": 2,
    "anti-u": -2,
    "d": -1,
    "anti-d": 1,
    "mu-": -3,
    "mu+": 3,
    "nu_mu": 0,
    "anti-nu_mu": 0,
    "c": 2,
    "anti-c": -2,
    "s": -1,
    "anti-s": 1,
    "tau-": -3,
    "tau+": 3,
    "nu_tau": 0,
    "anti-nu_tau": 0,
    "t": 2,
    "anti-t": -2,
    "b": -1,
    "anti-b": 1,
    "p": 3,
    "anti-p": -3,
    "n": 0,
    "anti-n": 0,
    "gamma": 0,
    "H": 0,
    "W+": 3,
    "W-": -3,
    "Z": 0,
    "eta": 0,
    "phi": 0,
    "pi+": 3,
    "pi0": 0,
    "pi-": -3,
    "K+": 3,
    "K0": 0,
    "K-": -3,
    "anti-K0": 0,
    "K0S": 0,
    "K0L": 0,
    "B+": 3,
    "B0": 0,
    "B-": -3,
    "anti-B0": 0,
}


PARTICLE_CHARGE_CONJUGATES: dict[str, str] = {
    "h": "ah",
    "ah": "h",
    "h2": "ah2",
    "ah2": "h2",
    "h3": "ah3",
    "ah3": "h3",
    "e-": "e+",
    "e+": "e-",
    "nu_e": "anti-nu_e",
    "anti-nu_e": "nu_e",
    "u": "anti-u",
    "anti-u": "u",
    "d": "anti-d",
    "anti-d": "d",
    "mu-": "mu+",
    "mu+": "mu-",
    "nu_mu": "anti-nu_mu",
    "anti-nu_mu": "nu_mu",
    "c": "anti-c",
    "anti-c": "c",
    "s": "anti-s",
    "anti-s": "s",
    "tau-": "tau+",
    "tau+": "tau-",
    "nu_tau": "anti-nu_tau",
    "anti-nu_tau": "nu_tau",
    "t": "anti-t",
    "anti-t": "t",
    "b": "anti-b",
    "anti-b": "b",
    "p": "anti-p",
    "anti-p": "p",
    "n": "anti-n",
    "anti-n": "n",
    "gamma": "gamma",
    "H": "H",
    "W+": "W-",
    "W-": "W+",
    "Z": "Z",
    "eta": "eta",
    "phi": "phi",
    "pi+": "pi-",
    "pi0": "pi0",
    "pi-": "pi+",
    "K+": "K-",
    "K0": "anti-K0",
    "K-": "K+",
    "anti-K0": "K0",
    "K0S": "K0S",
    "K0L": "K0L",
    "B+": "B-",
    "B0": "anti-B0",
    "B-": "B+",
    "anti-B0": "B0",
}


def particle_charge_thirds(canonical_name: str) -> int | None:
    return PARTICLE_CHARGE_THIRDS.get(canonical_name)


def conjugate_canonical_name(canonical_name: str) -> str | None:
    return PARTICLE_CHARGE_CONJUGATES.get(canonical_name)

PDG_MAPPING_BY_CANONICAL_NAME = {
    mapping.canonical_name: mapping
    for mapping in PDG_PARTICLE_MAPPINGS
}

PDG_CANONICAL_NAME_BY_ALIAS = {
    alias: mapping.canonical_name
    for mapping in PDG_PARTICLE_MAPPINGS
    for alias in mapping.aliases
}

PHI_ENERGY_LEVEL_PATTERN = re.compile(r"^phi\(\d+(?:\.\d+)?\)(?:0|\+|-)?$")

REQUEST_ASSEMBLY_MAPPINGS: tuple[ParticleMapping, ...] = tuple(
    mapping
    for mapping in PDG_PARTICLE_MAPPINGS
    if mapping.particle_type == "assembly"
)

REQUEST_ASSEMBLY_IDS: tuple[str, ...] = tuple(mapping.canonical_id for mapping in REQUEST_ASSEMBLY_MAPPINGS)

REQUEST_ASSEMBLY_COUNTS = {
    mapping.canonical_id: {
        "electrinoCount": mapping.electrino_count,
        "positrinoCount": mapping.positrino_count,
    }
    for mapping in REQUEST_ASSEMBLY_MAPPINGS
}


def canonicalize_pdg_name(name: str) -> str:
    stripped = str(name).strip()
    if not stripped:
        return stripped
    if stripped in PDG_CANONICAL_NAME_BY_ALIAS:
        return PDG_CANONICAL_NAME_BY_ALIAS[stripped]
    lowered = stripped.lower()
    if PHI_ENERGY_LEVEL_PATTERN.fullmatch(lowered):
        return "phi"
    return PDG_CANONICAL_NAME_BY_ALIAS.get(lowered, stripped)


def lookup_particle_mapping(name: str) -> ParticleMapping | None:
    return PDG_MAPPING_BY_CANONICAL_NAME.get(canonicalize_pdg_name(name))
